### ISSUE TITLE
运行crawl_webpage_demo例子不满足预期

### ISSUE THREAD

**Issue by thunder95** [shibing624/agentica#12]
### Describe the bug
运行crawl_webpage_demo例子不满足预期：
1. 模型推理一次解析两个tool，网页爬取的结果没有传入到文件保存save_file，content为空字符串
2. 总结回复时，将tool分析结果传入到messages，重复解析出2个tool，导致agent运行一直无法停止

### To Reproduce
python crawl_webpage_demo.py
ollama: qwen2.5 3B模型

请大佬给一些建议，如何优化。另外，大佬后续计划会对这个repo持续更新吗？

**Comment by shibing624** [comment]
需要用gpt4o,其他模型效果无法满足预期。
